use netflics;
#Todos los planes que se usaran en la base
insert into plan values(1,'Basico',99.00);
insert into plan values(2,'Estandar',129.00);
insert into plan values(3,'Premium',159.00);
select * from plan;
#Creación de los usuarios
insert into usuarios values('001','Pedro Luna Perez','pedro@gmail.com','passdepedro1','832145474587',1);
insert into usuarios values('002','Juan Sanchez Rivera','juan10@gmail.com','passdejuan1','859632147541',2);
insert into usuarios values('003','Arturo Lopez Casas','arturito69@gmail.com','passdearturo1','825471489632',3);
insert into usuarios values('004','Christian Gonzales Ramirez','chris666@gmail.com','passdechris1','847512856935',3);
select * from usuarios;
#Agregar pagos 
insert into pagos values('001',99.00,1,'001','2016/11/03');
insert into pagos values('002',129.00,2,'002','2016/11/04');
insert into pagos values('003',159.00,3,'003','2016/11/03');
insert into pagos values('004',159.00,3,'004','2016/11/04');
select * from pagos;
#Creación de perfiles
insert into perfiles values('001','P01','Novia de Pedro',19,1);
insert into perfiles values('001','P02','Pedro',20,1);
insert into perfiles values('001','P03','Mama de Pedro',45,1);
insert into perfiles values('002','P01','Novia de Juan',17,2);
insert into perfiles values('002','P02','Juan',20,2);
insert into perfiles values('002','P03','Papa de Juan',37,2);
insert into perfiles values('003','P01','Arturo',18,3);
insert into perfiles values('003','P02','Hermano de Arturo',25,3);
insert into perfiles values('003','P03','Hermana de Arturo',16,3);
insert into perfiles values('004','P01','Christian',25,3);
insert into perfiles values('004','P02','Esposa de Christian',26,3);
insert into perfiles values('004','P03','Suegra de Christian',42,3);
select * from perfiles;
#Añadir titulos
#####1er Titulo
insert into titulos values('T01','Doctor Strange','Después de que Stephen Strange, el mejor neurocirujano del mundo, se ve involucrado en un accidente de coche que termina arruinando su carrera, se embarca en un viaje de sanación, donde se encuentra con un ser misterioso llamado El Ancestral, quien le enseñará el mundo de las artes místicas.','13',2016,'Pelicula');
insert into titulos values('T02','House M.D.','La serie gira alrededor del Dr. Gregory House, un misántropo genio de la medicina, ególatra y de fuerte y marcada personalidad que dirige el Departamento de Diagnóstico Médico del ficticio Hospital Universitario Princeton-Plainsboro de Nueva Jersey, dirigido por la Dra. Lisa Cuddy.','ND',2004,'Serie');
insert into titulos values('T03','The Big Bang Theory','Leonard y Sheldon son estudiantes destacados en Caltech , amigos a su vez de Howard y Raj, que son presentados como unos completos geeks, alejados de las inquietudes y problemas de la gente común. En el curso de la serie se muestra la dificultad de los protagonistas masculinos para relacionarse con personas de fuera de su entorno, principalmente de sexo femenino, dando lugar a situaciones cómicas.','13',2007,'Serie');
insert into titulos values('T04','Naruto','Naruto Uzumaki es un ninja adolescente que tiene encerrado en su interior al «Zorro de Nueve Colas». Doce años antes del inicio de la serie, este demonio atacó a la Aldea Oculta de la Hoja, matando a muchas personas.','13',2016,'Serie');
insert into titulos values('T05','Dragon Ball Z: La Batalla de los Dioses','Aproximadamente cuatro años han pasado desde la batalla titánica contra Majin Buu, la cual determinó el destino de todo el universo. Desde el planeta Sagrado Kibito-shin y Kaio-shin Anciano discuten telepática-mente con Kaio del Norte sobre el temprano despertar de Bills.','13',2013,'Pelicula');
insert into titulos values('T06','Siempre a tu lado, Hachiko','La película empieza en la época presente, donde varios alumnos realizan una narración oral sobre sus héroes favoritos a la clase. Uno de los alumnos, Ronnie, empieza a contar la historia de Hachikō, el perro de su abuelo.','3',2009,'Pelicula');
insert into titulos values('T07','Grey´s Anatomy','«Grey´s Anatomy» sigue la vida de los residentes en el ficticio Grey-Sloan Memorial Hospital.','13',205,'Serie');
insert into titulos values('T08','Bob Esponja','El protagonista, que vive en el fondo del océano Pacífico, en la ciudad submarina de Fondo de Bikini, es una esponja marina rectangular y de color amarillo, llamada Bob Esponja Pantalones Cuadrados.','3',1999,'Serie');
insert into titulos values('T09','Metalocalypse','Metalocalypse sigue las aventuras de la banda de death metal, Dethklok, parte norteamericana y parte norte-escandinava.','18',2006,'Serie');
insert into titulos values('T10','Gravity Falls','La serie se trata de una historia de dos hermanos mellizos llamados Dipper Pines y Mabel Pines, quienes pasan sus vacaciones de verano visitando a su tío abuelo Stanley en una cabaña ubicada en un pueblo de Oregón llamado Gravity Falls, en el cual suceden cosas paranormales y sobrenaturales.','7',2012,'Serie');
select * from titulos;
#Añadir lista de generos utilizados
insert into generos values('G01','Superheroes');
insert into generos values('G02','Accion');
insert into generos values('G03','Fantasia');
insert into generos values('G04','Aventuras');
insert into generos values('G05','Drama');
insert into generos values('G06','Comedia');
insert into generos values('G07','Anime');
insert into generos values('G08','Shonen');
insert into generos values('G09','Artes Marciales');
insert into generos values('G10','Infantil');
insert into generos values('G11','Novela');
insert into generos values('G12','Caricaturas');
insert into generos values('G13','Musica');
insert into generos values('G14','Gore');
insert into generos values('G15','Ciencia Ficcion');
#Relacionar las peliculas con sus respectivos generos
insert into titulogenero values('G01','T01');
insert into titulogenero values('G02','T01');
insert into titulogenero values('G03','T01');
insert into titulogenero values('G04','T01');
insert into titulogenero values('G05','T02');
insert into titulogenero values('G06','T02');
insert into titulogenero values('G06','T03');
insert into titulogenero values('G02','T04');
insert into titulogenero values('G04','T04');
insert into titulogenero values('G05','T04');
insert into titulogenero values('G07','T04');
insert into titulogenero values('G08','T04');
insert into titulogenero values('G07','T05');
insert into titulogenero values('G02','T05');
insert into titulogenero values('G09','T05');
insert into titulogenero values('G10','T05');
insert into titulogenero values('G05','T06');
insert into titulogenero values('G05','T07');
insert into titulogenero values('G11','T07');
insert into titulogenero values('G06','T08');
insert into titulogenero values('G12','T08');
insert into titulogenero values('G03','T09');
insert into titulogenero values('G06','T09');
insert into titulogenero values('G13','T09');
insert into titulogenero values('G14','T09');
insert into titulogenero values('G12','T10');
insert into titulogenero values('G06','T10');
#Agregar las resoluciones que se van a trabajar
insert into calidades values('C1','720x480');
insert into calidades values('C2','1280x720');
insert into calidades values('C3','1920x1080');
insert into calidades values('C4','3840x2160');
#Relacionar las calidades con las series,peliculas
insert into tituloCalidad values('T01','C1');
insert into tituloCalidad values('T01','C2');
insert into tituloCalidad values('T01','C3');
insert into tituloCalidad values('T01','C4');
insert into tituloCalidad values('T02','C1');
insert into tituloCalidad values('T02','C2');
insert into tituloCalidad values('T02','C3');
insert into tituloCalidad values('T03','C1');
insert into tituloCalidad values('T03','C2');
insert into tituloCalidad values('T03','C3');
insert into tituloCalidad values('T04','C1');
insert into tituloCalidad values('T04','C2');
insert into tituloCalidad values('T04','C3');
insert into tituloCalidad values('T05','C1');
insert into tituloCalidad values('T05','C2');
insert into tituloCalidad values('T05','C3');
insert into tituloCalidad values('T05','C4');
insert into tituloCalidad values('T06','C1');
insert into tituloCalidad values('T06','C2');
insert into tituloCalidad values('T07','C1');
insert into tituloCalidad values('T07','C2');
insert into tituloCalidad values('T07','C3');
insert into tituloCalidad values('T08','C1');
insert into tituloCalidad values('T08','C2');
insert into tituloCalidad values('T08','C3');
insert into tituloCalidad values('T09','C1');
insert into tituloCalidad values('T09','C2');
insert into tituloCalidad values('T09','C3');
insert into tituloCalidad values('T10','C1');
insert into tituloCalidad values('T10','C2');
insert into tituloCalidad values('T10','C3');
insert into tituloCalidad values('T10','C4');
#Agregar actores (2 por pelicula/serie)
insert into actores values('A01','Benedict Cumberbatch');
insert into actores values('A02','Chiwetel Ejiofor');
insert into actores values('A03','Hugh Laurie');
insert into actores values('A04','Lisa Edelstein');
insert into actores values('A05','Johnny Galecki');
insert into actores values('A06','Jim Parsons');
insert into actores values('A07','Naruto Uzumaki');
insert into actores values('A08','Sasuke Uchiha');
insert into actores values('A09','Son Goku');
insert into actores values('A10','Vegeta');
insert into actores values('A11','Richard Gere');
insert into actores values('A12','Joan Allen');
insert into actores values('A13','Ellen Pompeo');
insert into actores values('A14','Justin Chambers');
insert into actores values('A15','Tom Kenny');
insert into actores values('A16','Bill Fagerbakke');
insert into actores values('A17','Nathan Explosion');
insert into actores values('A18','Toki Wartooth');
insert into actores values('A19','Mabel Pines');
insert into actores values('A20','Dipper Pines');
#Relacionar los actores/personajes con sus respectivas series/peliculas
insert into tituloactores values('A01','T01');
insert into tituloactores values('A02','T01');
insert into tituloactores values('A03','T02');
insert into tituloactores values('A04','T02');
insert into tituloactores values('A05','T03');
insert into tituloactores values('A06','T03');
insert into tituloactores values('A07','T04');
insert into tituloactores values('A08','T04');
insert into tituloactores values('A09','T05');
insert into tituloactores values('A10','T05');
insert into tituloactores values('A11','T06');
insert into tituloactores values('A12','T06');
insert into tituloactores values('A13','T07');
insert into tituloactores values('A14','T07');
insert into tituloactores values('A15','T08');
insert into tituloactores values('A16','T08');
insert into tituloactores values('A17','T09');
insert into tituloactores values('A18','T09');
insert into tituloactores values('A19','T10');
insert into tituloactores values('A20','T10');
#Agregar los directores en su respectiva tabla
insert into directores values('D01','Scott Derrickson');
insert into directores values('D02','David Shore');
insert into directores values('D03','Chuck Lorre');
insert into directores values('D04','Hayatto Date');
insert into directores values('D05','Masahiro Hosoda');
insert into directores values('D06','Lasse Hallström');
insert into directores values('D07','Shonda Rhimes');
insert into directores values('D08','Stephen Hillenburg');
insert into directores values('D09','Brendon Small');
insert into directores values('D10','Alex Hirsch');
#Relacionar los directores con su respectiva serie/pelicula
insert into titulodirectores values('D01','T01');
insert into titulodirectores values('D02','T02');
insert into titulodirectores values('D03','T03');
insert into titulodirectores values('D04','T04');
insert into titulodirectores values('D05','T05');
insert into titulodirectores values('D06','T06');
insert into titulodirectores values('D07','T07');
insert into titulodirectores values('D08','T08');
insert into titulodirectores values('D09','T09');
insert into titulodirectores values('D10','T10');
select * from usuarios where idUsuario='001';